# Copyright 2025 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

from collections.abc import Sequence
from dataclasses import dataclass, field
from enum import StrEnum, auto
from typing import Any, TypeAlias, TypedDict

from dataclasses_json import DataClassJsonMixin, config

from faith._internal.algo.matching import AnswerFormat
from faith._internal.metrics.types import Labeling
from faith._internal.types.flags import GenerationMode
from faith._types.records.prompt_record import PromptRecord

ChatConversation: TypeAlias = list[dict[str, str]]


class _Metadata(TypedDict):
    """Represents the metadata associated with a log record."""

    data_hash: str
    version: str


@dataclass(frozen=True)
class GenerationError(DataClassJsonMixin):
    """Record of an error that occurred during generation."""

    title: str
    details: str | None = None


@dataclass(frozen=True)
class ChatResponse(DataClassJsonMixin):
    """Record of a model chat session divided into several parts.

    Input/Output Records: the first way to divide a chat session is into its input
    and output parts. This division means that portions of the assistant's final
    message are actually in the input, as they are provided as part of the prompt
    template rather than generated by the model. The input/output division includes:
    - prompt: The original prompt given to the LLM as input.
    - output: The full output generated by the LLM.

    Request/Response Records: the second way to divide a chat session is into its
    request and response parts as defined by the user-assistant interaction. This
    division means that the input includes all messages before the final assistant
    message, and the output is just the final assistant message. The request/response
    division includes:
    - request: The request corresponds to all input before the final assistant message.
    - response: The response corresponds to the final assistant message.
    - answer: The portion of the response that is delimited as an answer; e.g., for
        reasoning models this would be the final answer after the reasoning block.
    """

    # The full output generated by the LLM.
    output_text: str
    output_token_ids: Sequence[int] | None = None
    num_output_tokens: int | None = None

    # The original prompt given to the LLM as input.
    prompt_text: str | None = None
    prompt_token_ids: Sequence[int] | None = None
    num_prompt_tokens: int | None = None

    # The request corresponds to all input before the final assistant message.
    request_text: str | None = None
    request_token_ids: Sequence[int] | None = None
    num_request_tokens: int | None = None

    # The response corresponds to the final assistant message.
    response_text: str | None = None
    response_token_ids: Sequence[int] | None = None
    num_response_tokens: int | None = None

    # The answer corresponds to the part of the response that is delimited as an answer.
    answer_text: str | None = None
    answer_token_ids: Sequence[int] | None = None
    num_answer_tokens: int | None = None

    max_token_halt: bool | None = None


@dataclass(frozen=True)
class TokenPred(DataClassJsonMixin):
    """Record of tokens and their corresponding IDs."""

    token: str
    token_id: int
    logprob: float
    rank: int | None = None


@dataclass
class ModelRecord(DataClassJsonMixin):
    """Represents the model data associated with a log record."""

    prompt: str | ChatConversation
    answer_symbol_ids: dict[str, int]

    logits: list[list[TokenPred]] | None = field(
        default=None, metadata=config(exclude=lambda x: x is None)
    )
    next_token: ChatResponse | None = field(
        default=None, metadata=config(exclude=lambda x: x is None)
    )
    chat_comp: ChatResponse | None = field(
        default=None, metadata=config(exclude=lambda x: x is None)
    )
    error: GenerationError | None = field(
        default=None, metadata=config(exclude=lambda x: x is None)
    )

    def reset_to_mode(self, mode: GenerationMode) -> None:
        """Resets the model data to only include response fields for the specified generation mode."""
        if mode != GenerationMode.LOGITS:
            self.logits = None
        if mode != GenerationMode.NEXT_TOKEN:
            self.next_token = None
        if mode != GenerationMode.CHAT_COMPLETION:
            self.chat_comp = None
        self.error = None


@dataclass(frozen=True)
class RecordStats(DataClassJsonMixin):
    """Statistics computed for a single record by a log grader."""

    label: Labeling | None
    prediction: Labeling | None
    answer_format: AnswerFormat = field(
        metadata=config(decoder=AnswerFormat.from_string, encoder=str)
    )
    subject: str | None = None
    log_probs: dict[str, float] | None = None
    num_output_tokens: int | None = None
    max_token_halt: bool | None = None
    scores: dict[str, Any] | None = None


@dataclass
class Record(DataClassJsonMixin):
    """Represents a log record used to track individual queries to a model."""

    metadata: _Metadata
    data: PromptRecord
    model_data: ModelRecord
    stats: RecordStats | None = None


class RecordStatus(StrEnum):
    """Indicates whether a record is clean (unchanged) or dirty (new or updated)."""

    CLEAN = auto()
    DIRTY = auto()
