# Copyright 2025 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

from collections.abc import Sequence
from dataclasses import dataclass, field
from typing import TypeAlias

from dataclasses_json import DataClassJsonMixin, config

ChatConversation: TypeAlias = list[dict[str, str]]


@dataclass(frozen=True)
class GenerationError(DataClassJsonMixin):
    """Record of an error that occurred during generation."""

    title: str
    details: str | None = field(
        default=None, metadata=config(exclude=lambda x: x is None)
    )


@dataclass(frozen=True)
class ChatResponse(DataClassJsonMixin):
    """Record of a model chat session divided into several parts.

    Input/Output Records: the first way to divide a chat session is into its input
    and output parts. This division means that portions of the assistant's final
    message are actually in the input, as they are provided as part of the prompt
    template rather than generated by the model. The input/output division includes:
    - prompt: The original prompt given to the LLM as input.
    - output: The full output generated by the LLM.

    Request/Response Records: the second way to divide a chat session is into its
    request and response parts as defined by the user-assistant interaction. This
    division means that the input includes all messages before the final assistant
    message, and the output is just the final assistant message. The request/response
    division includes:
    - request: The request corresponds to all input before the final assistant message.
    - response: The response corresponds to the final assistant message.
    - answer: The portion of the response that is delimited as an answer; e.g., for
        reasoning models this would be the final answer after the reasoning block.
    """

    # The full output generated by the LLM.
    output_text: str
    output_token_ids: Sequence[int] | None = field(
        default=None, metadata=config(exclude=lambda x: x is None)
    )
    num_output_tokens: int | None = field(
        default=None, metadata=config(exclude=lambda x: x is None)
    )

    # The original prompt given to the LLM as input.
    prompt_text: str | None = field(
        default=None, metadata=config(exclude=lambda x: x is None)
    )
    prompt_token_ids: Sequence[int] | None = field(
        default=None, metadata=config(exclude=lambda x: x is None)
    )
    num_prompt_tokens: int | None = field(
        default=None, metadata=config(exclude=lambda x: x is None)
    )

    # The request corresponds to all input before the final assistant message.
    request_text: str | None = field(
        default=None, metadata=config(exclude=lambda x: x is None)
    )
    request_token_ids: Sequence[int] | None = field(
        default=None, metadata=config(exclude=lambda x: x is None)
    )
    num_request_tokens: int | None = field(
        default=None, metadata=config(exclude=lambda x: x is None)
    )

    # The response corresponds to the final assistant message.
    response_text: str | None = field(
        default=None, metadata=config(exclude=lambda x: x is None)
    )
    response_token_ids: Sequence[int] | None = field(
        default=None, metadata=config(exclude=lambda x: x is None)
    )
    num_response_tokens: int | None = field(
        default=None, metadata=config(exclude=lambda x: x is None)
    )

    # The answer corresponds to the part of the response that is delimited as an answer.
    answer_text: str | None = field(
        default=None, metadata=config(exclude=lambda x: x is None)
    )
    answer_token_ids: Sequence[int] | None = field(
        default=None, metadata=config(exclude=lambda x: x is None)
    )
    num_answer_tokens: int | None = field(
        default=None, metadata=config(exclude=lambda x: x is None)
    )

    max_token_halt: bool | None = field(
        default=None, metadata=config(exclude=lambda x: x is None)
    )


@dataclass(frozen=True)
class TokenPred(DataClassJsonMixin):
    """Record of tokens and their corresponding IDs."""

    token: str
    token_id: int
    logprob: float
    rank: int | None = field(default=None, metadata=config(exclude=lambda x: x is None))
