# Copyright 2025 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

---
# This workflow does the following every time the version.txt file changes:
#
# 1. Parse the latest release version from the version.txt file.
# 2. Create a new tag using the release version.
# 3. Create a new GitHub release (the bundle and whl files will be attached).

name: "tag and release"

on:
  push:
    branches:
      - "main"
      - "release-*"
    paths:
      - "version.txt"
      - ".github/workflows/create-release.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  statuses: read

jobs:
  get-version:
    name: "get version from version.txt"
    runs-on: ubuntu-latest
    outputs:
      faith_version: ${{ steps.global_var.outputs.faith_version }}
    steps:
      - name: "🔒 harden runner"
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit
      - name: "📦 checkout repository"
        uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231
        with:
          persist-credentials: false
      - name: "⚙️ set global variables"
        env:
          MY_REF_NAME: "${{ github.ref_name }}"
        id: global_var
        run: |
          echo "branch=$MY_REF_NAME" >> "$GITHUB_OUTPUT"
          read -r VERSION < version.txt
          export MY_VERSION="$VERSION"
          export PREFIX=""
          if [[ "$MY_REF_NAME" != "main" ]] && \
             [[ "$MY_REF_NAME" != "release-*" ]]; then
            export PREFIX="$MY_REF_NAME-"
          fi
          echo "faith_version=${PREFIX}${MY_VERSION}" >> "$GITHUB_OUTPUT"

  create-tag:
    name: "create tag"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      statuses: write
    needs: [get-version]
    steps:
      - name: "🔒 harden runner"
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit
      - name: "📦 checkout repository"
        uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231
        with:
          persist-credentials: true
      - name: "🏷️ create git tag"
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MYTAG: "${{ needs.get-version.outputs.faith_version }}"
        run: |
          echo "INFO: Tagging HEAD to [$MYTAG]"
          git log --oneline -n 5
          git config --global user.email "action@github.com"
          git config --global user.name "Cisco-Foundation-AI"
          git tag -a "${MYTAG}" \
            -m "Foundation-AI's Testing Hub Release $MYTAG" HEAD
          git push origin "${MYTAG}"

  release:
    name: "release"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      statuses: write
    needs: [get-version, create-tag]
    steps:
      - name: "🔒 harden runner"
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit
      - name: "📦 checkout repository"
        uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231
        with:
          persist-credentials: false
      - name: "🚀 create a GitHub release"
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MYTAG: "${{ needs.get-version.outputs.faith_version }}"
        run: |
          gh release create "${MYTAG}" \
            --title "${MYTAG}" \
            --generate-notes
