# Copyright 2025 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

---
name: "unit test python"

on:
  push:
  workflow_dispatch:

# Declare default permissions as read-only
permissions: read-all

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }} @ ${{ ((github.ref_name == 'main') && github.run_id) || ''}}
  cancel-in-progress: ${{ !( github.ref_name == 'main') }}

jobs:
  unit-tests:
    runs-on: ubuntu-22.04-x86_64-large
    permissions:
      contents: read
    steps:
      - name: "🔒 harden runner"
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit
      - name: "📦 checkout repository"
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "🐍 setup python via uv"
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: "3.11"
          enable-cache: true
      - name: "📥 install packages"
        run: |
          uv venv
          uv pip install -e '.[test]'
      - name: "🧪 run all unit tests"
        run: |
          source .venv/bin/activate
          make test_all
